# Generated by Django 5.0.1 on 2024-02-01 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0002_restaurantmetadata"),
        ("tournaments", "0010_rename_address_tournament_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurantmetadata",
            name="tournament",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="tournament",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="tournaments.tournament",
            ),
            preserve_default=False,
        ),
    ]
