# Generated by Django 5.0.1 on 2024-02-27 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0004_remove_restaurant_location_restaurant_majorcity"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantmetadata",
            name="food_type",
            field=models.CharField(
                choices=[
                    ("American", "American"),
                    ("Buffet", "Buffet"),
                    ("Chinese", "Chinese"),
                    ("Indian", "Indian"),
                    ("Italian", "Italian"),
                    ("Japanese", "Japanese"),
                    ("Korean", "Korean"),
                    ("Mediterranean", "Mediterranean"),
                    ("Mexican", "Mexican"),
                    ("Thai", "Thai"),
                ],
                default="American",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="restaurantmetadata",
            name="meal_quality_rating",
            field=models.DecimalField(
                decimal_places=1,
                default=5.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="restaurantmetadata",
            name="parking_size",
            field=models.CharField(
                choices=[("Small", "Small"), ("Medium", "Medium"), ("Large", "Large")],
                default="Medium",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="restaurantmetadata",
            name="payment_process",
            field=models.CharField(
                choices=[
                    ("Smooth", "Smooth"),
                    ("Average", "Average"),
                    ("Rough", "Rough"),
                ],
                default="Smooth",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="restaurantmetadata",
            name="seating_time",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "10 minutes"),
                    (20, "20 minutes"),
                    (30, "30 minutes"),
                    (40, "40 minutes"),
                    (50, "50 minutes"),
                    (60, "1 hour"),
                    (70, "1 hour 10 minutes"),
                    (80, "1 hour 20 minutes"),
                    (90, "1 hour 30 minutes"),
                ],
                default=30,
            ),
        ),
        migrations.AddField(
            model_name="restaurantmetadata",
            name="service_quality_rating",
            field=models.DecimalField(
                decimal_places=1,
                default=5.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
