# Generated by Django 5.0.1 on 2024-02-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0007_alter_restaurantmetadata_food_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantmetadata",
            name="food_type",
            field=models.CharField(
                choices=[
                    ("Other", "Other"),
                    ("American", "American"),
                    ("Buffet", "Buffet"),
                    ("Chinese", "Chinese"),
                    ("Greek", "Greek"),
                    ("Indian", "Indian"),
                    ("Italian", "Italian"),
                    ("Japanese", "Japanese"),
                    ("Korean", "Korean"),
                    ("Mediterranean", "Mediterranean"),
                    ("Mexican", "Mexican"),
                    ("Thai", "Thai"),
                ],
                default="Other",
                max_length=100,
            ),
        ),
    ]
