# Generated by Django 5.0.1 on 2024-03-13 12:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default='0.0')),
                ('longitude', models.FloatField(default='0.0')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='yht tournament', max_length=100)),
                ('company', models.CharField(default='yht', max_length=100)),
                ('website', models.CharField(default='https://www.yhtreviews.com', max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('reff_rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('comms_rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('parking_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('parking_valet', models.BooleanField(default=False)),
                ('parking_cost', models.CharField(choices=[('free', 'Free'), ('$0-$5', '$0 - $5'), ('$5-$10', '$5 - $10'), ('$10-$15', '$10 - $15'), ('$15-$20', '$15 - $20'), ('$20-$25', '$20 - $25'), ('$25-$30', '$25 - $30')], default='free', max_length=10)),
                ('stay_and_play', models.BooleanField(default=False)),
                ('extended_checkout', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.location')),
            ],
        ),
    ]
