# Generated by Django 5.0.1 on 2024-03-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournament_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='draft_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
