# Generated by Django 5.0.1 on 2024-03-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_alter_tournament_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='company',
            field=models.CharField(choices=[('YHT', 'YHT'), ('CAN/AM', 'CAN/AM'), ('CHE', 'CHE'), ('EliteAMSports', 'EliteAMSports'), ('MyHockey', 'MyHockey'), ('OneHockey', 'OneHockey'), ('RSG', 'RSG'), ('SES', 'SES'), ('TCS', 'TCS'), ('WPG', 'WPG')], default='yht', max_length=100),
        ),
    ]
