# Generated by Django 5.0.1 on 2024-03-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_alter_tournament_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(default='All', max_length=50),
        ),
    ]
