# Generated by Django 5.0.1 on 2024-03-15 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_location_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='comms_rating',
            field=models.FloatField(default=4.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='reff_rating',
            field=models.FloatField(default=4.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
