# Generated by Django 5.0.1 on 2024-03-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_alter_tournament_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='address',
            field=models.CharField(default='5555 default address, DF 1234 USA', max_length=255),
        ),
    ]
