# Generated by Django 5.0.1 on 2024-03-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_alter_tournament_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='company',
        ),
    ]
