# Generated by Django 5.0.1 on 2024-03-24 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_tournamentcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.tournamentcompany'),
        ),
    ]
