# Generated by Django 5.0.1 on 2024-03-25 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_location_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
    ]
