# Generated by Django 5.0.1 on 2024-03-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_remove_location_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
