# Generated by Django 5.0.1 on 2024-03-25 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_tournament_majorcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='rating',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
