# Generated by Django 5.0.1 on 2024-04-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_remove_tournament_downvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
