# Generated by Django 5.0.1 on 2024-04-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0025_agecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='levels_of_play',
            field=models.ManyToManyField(blank=True, to='tournament.agecategory'),
        ),
    ]
