# Generated by Django 5.0.1 on 2024-04-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0027_agegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='age_groups',
            field=models.ManyToManyField(blank=True, to='tournament.agegroup'),
        ),
    ]
