# Generated by Django 5.0.1 on 2024-04-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0029_alter_agegroup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agegroup',
            options={},
        ),
        migrations.AddField(
            model_name='agegroup',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
