# Generated by Django 5.0.1 on 2024-04-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0030_alter_agegroup_options_agegroup_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
