# Generated by Django 5.0.1 on 2024-04-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0031_tournamenthardware'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamenthardware',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
