# Generated by Django 5.0.1 on 2024-04-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0033_tournament_first_place_hardware_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agecategory',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
