# Generated by Django 5.0.1 on 2024-04-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0037_tournament_other_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='minimum_games_played',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3')], default='3', max_length=10),
        ),
    ]
