# Generated by Django 5.0.1 on 2024-04-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0039_tournament_tournament_director_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='start_date',
        ),
    ]
