# Generated by Django 5.0.1 on 2024-04-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0040_remove_tournament_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='early_bird_discount',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ("I don't Know", "I don't Know")], default="I Don't Know", max_length=12),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='extended_checkout',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ("I don't Know", "I don't Know")], default="I Don't Know", max_length=12),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='multi_team_discount',
            field=models.CharField(choices=[('No', 'No'), ('2+', '2+'), ('3+', '3+')], default='No', max_length=12),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='other_discounts',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ("I don't Know", "I don't Know")], default="I Don't Know", max_length=12),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='stay_and_play',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ("I don't Know", "I don't Know")], default="I Don't Know", max_length=12),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_director',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ("I don't Know", "I don't Know")], default="I Don't Know", max_length=12),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='usa_hockey_sanction',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ("I don't Know", "I don't Know")], default="I Don't Know", max_length=12),
        ),
    ]
