# Generated by Django 5.0.1 on 2024-04-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0042_parkingavailability_rink_parking_size_rink_rink_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rink',
            name='bathroom_state',
            field=models.CharField(choices=[('Pretty Clean', 'Pretty Clean'), ('Average', 'Average'), ('Nothing to Rave Home About', 'Nothing to Rave Home About'), ('Hose Shoes Off After Walk You Out', 'Hose Shoes Off After Walk You Out')], default='Pretty Clean', max_length=33),
        ),
        migrations.AddField(
            model_name='rink',
            name='director_present',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ("I don't Know", "I don't Know")], default="I Don't Know", max_length=12),
        ),
        migrations.AddField(
            model_name='rink',
            name='parking_cost',
            field=models.CharField(choices=[('free', 'Free'), ('$0-$5', '$0 - $5'), ('$5-$10', '$5 - $10'), ('$10-$15', '$10 - $15'), ('$15-$20', '$15 - $20'), ('$20-$25', '$20 - $25'), ('$25-$30', '$25 - $30')], default='Free', max_length=15),
        ),
        migrations.AddField(
            model_name='rink',
            name='parking_type',
            field=models.ManyToManyField(blank=True, to='tournament.parkingavailability'),
        ),
        migrations.AddField(
            model_name='rink',
            name='pro_shop',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ("I don't Know", "I don't Know")], default="I Don't Know", max_length=12),
        ),
        migrations.AddField(
            model_name='rink',
            name='snack_bar',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ("I don't Know", "I don't Know")], default="I Don't Know", max_length=12),
        ),
        migrations.AddField(
            model_name='rink',
            name='valet_parking',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ("I don't Know", "I don't Know")], default="I Don't Know", max_length=12),
        ),
    ]
