# Generated by Django 5.0.1 on 2024-04-19 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0044_remove_rink_parking_type_remove_rink_tournament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(default=datetime.date(2005, 1, 1)),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(default=datetime.date(2005, 1, 1)),
        ),
    ]
