# Generated by Django 5.0.1 on 2024-04-19 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0047_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='start_date',
        ),
    ]
