# Generated by Django 5.0.1 on 2024-04-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0048_remove_tournament_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
