# Generated by Django 5.0.1 on 2024-02-01 08:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0004_rename_address_location_street_and_more"),
        ("tournaments", "0010_rename_address_tournament_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entertainment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "rating_overall",
                    models.DecimalField(
                        decimal_places=1,
                        default=1.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.location",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournaments.tournament",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntertainmentMetadat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entertainment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entertainments.entertainment",
                        unique=True,
                    ),
                ),
            ],
            options={
                "unique_together": {("entertainment",)},
            },
        ),
    ]
