# Generated by Django 5.0.1 on 2024-02-01 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entertainments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entertainmentmetadat",
            name="entertainment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="entertainments.entertainment",
            ),
        ),
    ]
