# Generated by Django 5.0.1 on 2024-02-01 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entertainments", "0002_alter_entertainmentmetadat_entertainment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EntertainmentMetadat",
            new_name="EntertainmentMetadata",
        ),
    ]
