# Generated by Django 5.0.1 on 2024-02-23 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entertainments", "0003_rename_entertainmentmetadat_entertainmentmetadata"),
        ("locations", "0005_majorcity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entertainment",
            name="location",
        ),
        migrations.AddField(
            model_name="entertainment",
            name="majorcity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.majorcity",
            ),
        ),
    ]
