# Generated by Django 5.0.1 on 2024-02-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entertainments", "0004_remove_entertainment_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entertainmentmetadata",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("Amusement parks", "Amusement parks"),
                    (
                        "Arcades with kid-friendly games",
                        "Arcades with kid-friendly games",
                    ),
                    (
                        "Beaches or lakes for water activities",
                        "Beaches or lakes for water activities",
                    ),
                    ("Botanical gardens", "Botanical gardens"),
                    ("Bowling alleys", "Bowling alleys"),
                    ("Cafes with play areas", "Cafes with play areas"),
                    ("Children's shows or events", "Children's shows or events"),
                    ("Community sports events", "Community sports events"),
                    (
                        "Educational workshops or classes",
                        "Educational workshops or classes",
                    ),
                    (
                        "Gaming centers or esports arenas",
                        "Gaming centers or esports arenas",
                    ),
                    ("Indoor play areas", "Indoor play areas"),
                    ("Interactive science centers", "Interactive science centers"),
                    ("Live theaters or performances", "Live theaters or performances"),
                    ("Local events or festivals", "Local events or festivals"),
                    ("Local markets or fairs", "Local markets or fairs"),
                    ("Mini-golf courses", "Mini-golf courses"),
                    ("Movie theaters", "Movie theaters"),
                    ("Museums", "Museums"),
                    ("Nature trails or hiking spots", "Nature trails or hiking spots"),
                    ("Parks and playgrounds", "Parks and playgrounds"),
                    (
                        "Parades or community gatherings",
                        "Parades or community gatherings",
                    ),
                    ("Picnic areas", "Picnic areas"),
                    ("Planetariums", "Planetariums"),
                    ("Professional Sporting Event", "Professional Sporting Event"),
                    (
                        "Shopping centers with kid-friendly stores",
                        "Shopping centers with kid-friendly stores",
                    ),
                    (
                        "Sports complexes (for other sports)",
                        "Sports complexes (for other sports)",
                    ),
                    ("Swimming pools or water parks", "Swimming pools or water parks"),
                    ("Toy stores", "Toy stores"),
                    ("Trampoline parks", "Trampoline parks"),
                    ("Zoos and aquariums", "Zoos and aquariums"),
                ],
                default="Amusement parks",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="entertainmentmetadata",
            name="age_range",
            field=models.CharField(
                choices=[
                    ("8u", "8 and under"),
                    ("10u", "10 and under"),
                    ("12u", "12 and under"),
                    ("14u", "14 and under"),
                    ("16u", "16 and under"),
                    ("18u", "18 and under"),
                ],
                default="8u",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="entertainmentmetadata",
            name="parking_size",
            field=models.CharField(
                choices=[("Small", "Small"), ("Medium", "Medium"), ("Large", "Large")],
                default="Medium",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="entertainmentmetadata",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("All", "All"),
                    ("Card", "Card"),
                    ("Cash", "Cash"),
                    ("Apple Pay / Google Pay", "Apple Pay / Google Pay"),
                ],
                default="None",
                max_length=22,
            ),
        ),
        migrations.AddField(
            model_name="entertainmentmetadata",
            name="service_quality_rating",
            field=models.CharField(
                choices=[("Good", "Good"), ("Bad", "Bad")], default="Good", max_length=4
            ),
        ),
        migrations.AddField(
            model_name="entertainmentmetadata",
            name="serving_alcohol",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("All", "All"),
                    ("Beer", "Beer"),
                    ("Wine", "Wine"),
                    ("Liquor", "Liquor"),
                ],
                default="None",
                max_length=10,
            ),
        ),
    ]
