# Generated by Django 5.0.1 on 2024-01-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_remove_tournament_count_thumbs_down_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmetadata',
            name='parking_size',
            field=models.CharField(default='Medium', max_length=6, verbose_name=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')]),
        ),
        migrations.AlterField(
            model_name='tournamentmetadata',
            name='parking_cost',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=4),
        ),
        migrations.AlterField(
            model_name='tournamentmetadata',
            name='stay_and_play',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Idk', 'Idk')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='tournamentmetadata',
            name='tournament_company',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Idk', 'Idk')], default='Idk', max_length=3),
        ),
    ]
