# Generated by Django 5.0.1 on 2024-01-30 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_tournamentmetadata_stay_and_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmetadata',
            name='tournament',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament'),
        ),
    ]
