# Generated by Django 5.0.1 on 2024-01-30 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_tournamentmetadata_tournament'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentmetadata',
            unique_together={('tournament',)},
        ),
    ]
