# Generated by Django 5.0.1 on 2024-01-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_alter_tournamentmetadata_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmetadata',
            name='tournament_company',
            field=models.CharField(default='Idk', max_length=100),
        ),
    ]
