# Generated by Django 5.0.1 on 2024-01-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_alter_tournamentmetadata_tournament_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='tournament',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
