# Generated by Django 5.0.1 on 2024-01-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_rename_location_tournament_address_tournament_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='address',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='city',
        ),
    ]
