# Generated by Django 5.0.1 on 2024-02-20 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0005_majorcity"),
        ("tournaments", "0010_rename_address_tournament_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="location",
        ),
        migrations.AddField(
            model_name="tournament",
            name="majorcity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.majorcity",
            ),
        ),
    ]
