# Generated by Django 5.0.1 on 2024-02-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0012_rink"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="month",
            field=models.CharField(
                choices=[
                    ("January", "January"),
                    ("February", "February"),
                    ("March", "March"),
                    ("April", "April"),
                    ("May", "May"),
                    ("June", "June"),
                    ("July", "July"),
                    ("August", "August"),
                    ("September", "September"),
                    ("October", "October"),
                    ("November", "November"),
                    ("December", "December"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
