# Generated by Django 5.0.1 on 2024-02-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0013_tournament_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="company",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
