# Generated by Django 5.0.1 on 2024-02-26 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0016_tournament_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournamentmetadata",
            name="tournament_company",
        ),
    ]
