# Generated by Django 5.0.1 on 2024-02-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0018_alter_tournament_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="url",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
