# Generated by Django 5.0.1 on 2024-02-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0020_alter_tournament_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="url",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
