# Generated by Django 5.0.1 on 2024-02-26 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0022_tournamentmetadata_extended_checkout"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournamentmetadata",
            name="count_rinks",
        ),
        migrations.RemoveField(
            model_name="tournamentmetadata",
            name="rating_hotels",
        ),
    ]
