# Generated by Django 5.0.1 on 2024-02-27 16:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0005_majorcity"),
        ("tournaments", "0023_remove_tournamentmetadata_count_rinks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentmetadata",
            name="count_thumbs_up",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="tournamentmetadata",
            name="parking_cost",
            field=models.CharField(
                choices=[("Free", "Free"), ("Paid", "Paid")],
                default="Paid",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="tournamentmetadata",
            name="parking_valet",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tournamentmetadata",
            name="rating_comms",
            field=models.DecimalField(
                decimal_places=1,
                default=5.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tournamentmetadata",
            name="rating_reffing",
            field=models.DecimalField(
                decimal_places=1,
                default=5.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.location",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournaments.tournament",
                    ),
                ),
            ],
        ),
    ]
