# Generated by Django 5.0.1 on 2024-01-30 02:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntertainmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
                ('rating_overall', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('overview_text', models.TextField(validators=[django.core.validators.MaxLengthValidator(1200)])),
                ('name', models.CharField(default='', max_length=100)),
                ('activity_category', models.CharField(choices=[('Amusement parks', 'Amusement parks'), ('Zoos and aquariums', 'Zoos and aquariums'), ('Museums', 'Museums'), ('Botanical gardens', 'Botanical gardens'), ('Parks and playgrounds', 'Parks and playgrounds'), ('Nature trails or hiking spots', 'Nature trails or hiking spots'), ('Picnic areas', 'Picnic areas'), ('Beaches or lakes for water activities', 'Beaches or lakes for water activities'), ('Bowling alleys', 'Bowling alleys'), ('Mini-golf courses', 'Mini-golf courses'), ('Trampoline parks', 'Trampoline parks'), ('Indoor play areas', 'Indoor play areas'), ('Sports complexes (for other sports)', 'Sports complexes (for other sports)'), ('Swimming pools or water parks', 'Swimming pools or water parks'), ('Movie theaters', 'Movie theaters'), ('Live theaters or performances', 'Live theaters or performances'), ("Children's shows or events", "Children's shows or events"), ('Family-friendly restaurants', 'Family-friendly restaurants'), ('Cafes with play areas', 'Cafes with play areas'), ('Ice cream shops', 'Ice cream shops'), ('Local markets or fairs', 'Local markets or fairs'), ('Shopping centers with kid-friendly stores', 'Shopping centers with kid-friendly stores'), ('Toy stores', 'Toy stores'), ('Interactive science centers', 'Interactive science centers'), ('Educational workshops or classes', 'Educational workshops or classes'), ('Planetariums', 'Planetariums'), ('Arcades with kid-friendly games', 'Arcades with kid-friendly games'), ('Gaming centers or esports arenas', 'Gaming centers or esports arenas'), ('Local events or festivals', 'Local events or festivals'), ('Parades or community gatherings', 'Parades or community gatherings'), ('Community sports events', 'Community sports events')], default='Museums', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HotelSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
                ('rating_overall', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('overview_text', models.TextField(validators=[django.core.validators.MaxLengthValidator(1200)])),
                ('hotel_chain', models.CharField(default='Unknown', max_length=100)),
                ('room_price', models.DecimalField(decimal_places=2, default=100.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
                ('rating_overall', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('overview_text', models.TextField(validators=[django.core.validators.MaxLengthValidator(1200)])),
                ('object_type', models.CharField(default='Restaurant', max_length=50)),
                ('food_type', models.CharField(choices=[('American', 'American'), ('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Chinese', 'Chinese'), ('Korean', 'Korean'), ('Japanese', 'Japanese'), ('Indian', 'Indian'), ('Mediterranean', 'Mediterranean'), ('Thai', 'Thai')], default='American', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TournamentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
                ('rating_overall', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('overview_text', models.TextField(validators=[django.core.validators.MaxLengthValidator(1200)])),
                ('tournament_name', models.CharField(default='', max_length=100)),
                ('tournament_company', models.CharField(default='Idk', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
