# Generated by Django 5.0.1 on 2024-01-30 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entertainmentsubmission',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='hotelsubmission',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='restaurantsubmission',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='tournamentsubmission',
            old_name='location',
            new_name='address',
        ),
    ]
