# Generated by Django 5.0.1 on 2024-01-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_rename_location_entertainmentsubmission_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantsubmission',
            name='object_type',
        ),
        migrations.AddField(
            model_name='restaurantsubmission',
            name='restaurant',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
