# Generated by Django 5.0.1 on 2024-02-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "submissions",
            "0007_entertainmentsubmission_email_hotelsubmission_email_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entertainmentsubmission",
            name="address",
        ),
        migrations.RemoveField(
            model_name="hotelsubmission",
            name="address",
        ),
        migrations.RemoveField(
            model_name="restaurantsubmission",
            name="address",
        ),
        migrations.RemoveField(
            model_name="tournamentsubmission",
            name="address",
        ),
        migrations.AddField(
            model_name="entertainmentsubmission",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="entertainmentsubmission",
            name="country",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="entertainmentsubmission",
            name="state",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="entertainmentsubmission",
            name="street_address",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="entertainmentsubmission",
            name="zipcode",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="hotelsubmission",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="hotelsubmission",
            name="country",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="hotelsubmission",
            name="state",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="hotelsubmission",
            name="street_address",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="hotelsubmission",
            name="zipcode",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="restaurantsubmission",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="restaurantsubmission",
            name="country",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="restaurantsubmission",
            name="state",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="restaurantsubmission",
            name="street_address",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="restaurantsubmission",
            name="zipcode",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="tournamentsubmission",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="tournamentsubmission",
            name="country",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="tournamentsubmission",
            name="state",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="tournamentsubmission",
            name="street_address",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="tournamentsubmission",
            name="zipcode",
            field=models.CharField(default="", max_length=20),
        ),
    ]
