# Generated by Django 5.0.1 on 2024-02-28 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0008_remove_entertainmentsubmission_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entertainmentsubmission",
            name="rating_overall",
            field=models.DecimalField(
                decimal_places=1,
                default=5.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="hotelsubmission",
            name="rating_overall",
            field=models.DecimalField(
                decimal_places=1,
                default=5.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="restaurantsubmission",
            name="rating_overall",
            field=models.DecimalField(
                decimal_places=1,
                default=5.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tournamentsubmission",
            name="rating_overall",
            field=models.DecimalField(
                decimal_places=1,
                default=5.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
