# Generated by Django 5.0.1 on 2024-02-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0009_alter_entertainmentsubmission_rating_overall_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelsubmission",
            name="hotel_chain",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="restaurantsubmission",
            name="restaurant",
            field=models.CharField(default="", max_length=100),
        ),
    ]
