# Generated by Django 5.0.1 on 2024-03-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        ('tournament', '0009_alter_tournament_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='TournamentReview',
        ),
    ]
