# Generated by Django 5.0.1 on 2024-03-23 00:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0002_alter_entertainment_activity_type'),
        ('restaurant', '0004_alter_restaurant_food_type'),
        ('review', '0003_tournamentreview_comms_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntertainmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('comment', models.TextField()),
                ('service_rating', models.FloatField(default=4.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('entertainment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='entertainment.entertainment')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('comment', models.TextField()),
                ('meal_quality', models.FloatField(default=4.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('service_quality', models.FloatField(default=4.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurant.restaurant')),
            ],
        ),
    ]
