# Generated by Django 5.0.1 on 2024-03-25 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_entertainmentreview_restaurantreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainmentreview',
            name='rating',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='rating',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='tournamentreview',
            name='vote',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default='up', max_length=4),
        ),
    ]
