# Generated by Django 5.0.1 on 2024-03-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_entertainmentreview_rating_restaurantreview_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentreview',
            name='vote',
            field=models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], default='upvote', max_length=8),
        ),
    ]
