# Generated by Django 5.0.1 on 2024-04-19 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_tournamentreview_parking_notes'),
        ('rink', '0005_alter_rink_rink_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RinkReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('comment', models.TextField()),
                ('rink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rink.rink')),
            ],
        ),
    ]
