# Generated by Django 5.0.1 on 2024-04-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_hotelreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelreview',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
