# Generated by Django 5.0.1 on 2024-01-16 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('overall_rating', models.IntegerField(default=0)),
                ('thumbs_up', models.IntegerField(default=0)),
                ('thumbs_down', models.IntegerField(default=0)),
                ('number_of_rinks', models.IntegerField(default=1)),
                ('reffing_quality', models.CharField(choices=[('Poor', 'Poor'), ('Below Average', 'Below Average'), ('Average', 'Average'), ('Above Average', 'Above Average'), ('Excellent', 'Excellent')], max_length=15)),
                ('game_times_scheduled', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('runs_on_time', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('travelling_company', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('hotel_quality', models.CharField(choices=[('Poor', 'Poor'), ('Below Average', 'Below Average'), ('Average', 'Average'), ('Above Average', 'Above Average'), ('Excellent', 'Excellent')], max_length=15)),
                ('director_communication', models.CharField(choices=[('Poor', 'Poor'), ('Below Average', 'Below Average'), ('Average', 'Average'), ('Above Average', 'Above Average'), ('Excellent', 'Excellent')], max_length=15)),
                ('stay_and_play', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='HotelPositive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_type', models.CharField(max_length=100)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(max_length=100)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.tournament'),
        ),
    ]
