# Generated by Django 5.0.1 on 2024-01-30 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_of_review', models.DateField()),
                ('review_text', models.TextField(validators=[django.core.validators.MaxLengthValidator(1200)])),
                ('thumb_updown', models.CharField(choices=[('Thumbs Up', 'Thumbs Up'), ('Thumbs Down', 'Thumbs Down')], default='Thumbs Up', max_length=11)),
                ('rating_reffing', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('rating_comms', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('runs_on_time', models.CharField(choices=[('Runs Ontime', 'Runs Ontime'), ('1 Game Behind', '1 Game Behind'), ('1 or More Games Behind', '1 or More Games Behind'), ('Too Many Games Behind', 'Too Many Games Behind')], default='Runs Ontime', max_length=22)),
                ('parking_size', models.CharField(default='Medium', max_length=6, verbose_name=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')])),
                ('parking_valet', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Idk', 'Idk')], default='No', max_length=3)),
                ('parking_cost', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=4)),
                ('parking_notes', models.TextField(default='empty', max_length=250)),
                ('tournament_company', models.CharField(default='none', max_length=50)),
                ('count_rinks', models.IntegerField(default=1)),
                ('stay_and_play', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Idk', 'Idk')], default='No', max_length=3)),
                ('rating_hotels', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('extended_checkout', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Idk', 'Idk')], default='Idk', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
