# Generated by Django 5.0.1 on 2024-01-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentreview',
            name='tournament_company',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Idk', 'Idk')], default='Idk', max_length=3),
        ),
    ]
