# Generated by Django 5.0.1 on 2024-01-17 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_tournamentsubmission_review_rating_tournament_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tournamentsubmission',
            name='date',
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournamentsubmission',
            name='info',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
