# Generated by Django 5.0.1 on 2024-02-01 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_alter_tournamentreview_tournament_company"),
        ("tournaments", "0010_rename_address_tournament_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentreview",
            name="tournament",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="tournaments.tournament",
            ),
            preserve_default=False,
        ),
    ]
