# Generated by Django 5.0.1 on 2024-02-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0004_tournamentreview_tournament"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentreview",
            name="parking_size",
            field=models.CharField(
                choices=[("Small", "Small"), ("Medium", "Medium"), ("Large", "Large")],
                default="Medium",
                max_length=6,
            ),
        ),
    ]
