# Generated by Django 5.0.1 on 2024-02-20 19:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0005_alter_tournamentreview_parking_size"),
        ("tournaments", "0013_tournament_month"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentShortReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date_of_review", models.DateField()),
                (
                    "review_text",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(1200)]
                    ),
                ),
                (
                    "overall_rating",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
