# Generated by Django 5.0.1 on 2024-01-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_hotel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentsubmission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewing', 'Reviewing'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Pending', max_length=15),
        ),
    ]
