# Generated by Django 5.0.1 on 2024-02-26 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0007_remove_tournamentreview_tournament_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournamentreview",
            name="count_rinks",
        ),
        migrations.RemoveField(
            model_name="tournamentreview",
            name="rating_hotels",
        ),
    ]
