# Generated by Django 5.0.1 on 2024-01-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_tournamentsubmission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
