# Generated by Django 5.0.1 on 2024-02-27 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0008_remove_tournamentreview_count_rinks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentreview",
            name="parking_cost",
            field=models.CharField(
                choices=[("Free", "Free"), ("Paid", "Paid")],
                default="Paid",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="tournamentreview",
            name="parking_notes",
            field=models.TextField(default="n/a", max_length=250),
        ),
        migrations.AlterField(
            model_name="tournamentreview",
            name="rating_comms",
            field=models.DecimalField(
                decimal_places=1,
                default=5.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tournamentreview",
            name="rating_reffing",
            field=models.DecimalField(
                decimal_places=1,
                default=5.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tournamentreview",
            name="review_text",
            field=models.TextField(
                default="n/a",
                validators=[django.core.validators.MaxLengthValidator(1200)],
            ),
        ),
        migrations.AlterField(
            model_name="tournamentreview",
            name="stay_and_play",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Idk", "Idk")],
                default="Idk",
                max_length=3,
            ),
        ),
    ]
