# Generated by Django 5.0.1 on 2024-01-19 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='director_communication',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='game_times_scheduled',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='hotel_quality',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='number_of_rinks',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='reffing_quality',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='runs_on_time',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='stay_and_play',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='travelling_company',
        ),
        migrations.AddField(
            model_name='review',
            name='director_communication',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Below Average', 'Below Average'), ('Average', 'Average'), ('Above Average', 'Above Average'), ('Excellent', 'Excellent')], default='Excellent', max_length=15),
        ),
        migrations.AddField(
            model_name='review',
            name='hotel_quality',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Below Average', 'Below Average'), ('Average', 'Average'), ('Above Average', 'Above Average'), ('Excellent', 'Excellent')], default='Excellent', max_length=15),
        ),
        migrations.AddField(
            model_name='review',
            name='number_of_rinks',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='parking_cost',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], default='Free', max_length=4),
        ),
        migrations.AddField(
            model_name='review',
            name='parking_notes',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='review',
            name='reffing_quality',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Below Average', 'Below Average'), ('Average', 'Average'), ('Above Average', 'Above Average'), ('Excellent', 'Excellent')], default='Excellent', max_length=15),
        ),
        migrations.AddField(
            model_name='review',
            name='runs_on_time',
            field=models.CharField(choices=[('Runs Ontime', 'Runs Ontime'), ('1 Game Behind', '1 Game Behind'), ('1 or More Games Behind', '1 or More Games Behind'), ('Too Many Games Behind', 'Too Many Games Behind')], default='Runs Ontime', max_length=22),
        ),
        migrations.AddField(
            model_name='review',
            name='stay_and_play',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='review',
            name='thumbs_rating',
            field=models.CharField(choices=[('Thumbs Up', 'Thumbs Up'), ('Thumbs Down', 'Thumbs Down')], default='Thumbs Up', max_length=11),
        ),
        migrations.AddField(
            model_name='review',
            name='travelling_company',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='review',
            name='valet_parking',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='overall_rating',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='tournamentsubmission',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
