# Generated by Django 5.0.1 on 2024-02-27 20:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entertainments", "0006_alter_entertainmentmetadata_activity_type"),
        ("restaurants", "0007_alter_restaurantmetadata_food_type"),
        ("reviews", "0009_alter_tournamentreview_parking_cost_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntertainmentReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date_of_review", models.DateField()),
                (
                    "review_text",
                    models.TextField(
                        default="n/a",
                        validators=[django.core.validators.MaxLengthValidator(1200)],
                    ),
                ),
                (
                    "thumb_updown",
                    models.CharField(
                        choices=[
                            ("Thumbs Up", "Thumbs Up"),
                            ("Thumbs Down", "Thumbs Down"),
                        ],
                        default="Thumbs Up",
                        max_length=11,
                    ),
                ),
                (
                    "rating_overall",
                    models.DecimalField(
                        decimal_places=1,
                        default=5.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("Other", "Other"),
                            ("Amusement parks", "Amusement parks"),
                            (
                                "Arcades with kid-friendly games",
                                "Arcades with kid-friendly games",
                            ),
                            (
                                "Beaches or lakes for water activities",
                                "Beaches or lakes for water activities",
                            ),
                            ("Botanical gardens", "Botanical gardens"),
                            ("Bowling alleys", "Bowling alleys"),
                            ("Cafes with play areas", "Cafes with play areas"),
                            (
                                "Children's shows or events",
                                "Children's shows or events",
                            ),
                            ("Community sports events", "Community sports events"),
                            (
                                "Educational workshops or classes",
                                "Educational workshops or classes",
                            ),
                            (
                                "Gaming centers or esports arenas",
                                "Gaming centers or esports arenas",
                            ),
                            ("Indoor play areas", "Indoor play areas"),
                            (
                                "Interactive science centers",
                                "Interactive science centers",
                            ),
                            (
                                "Live theaters or performances",
                                "Live theaters or performances",
                            ),
                            ("Local events or festivals", "Local events or festivals"),
                            ("Local markets or fairs", "Local markets or fairs"),
                            ("Mini-golf courses", "Mini-golf courses"),
                            ("Movie theaters", "Movie theaters"),
                            ("Museums", "Museums"),
                            (
                                "Nature trails or hiking spots",
                                "Nature trails or hiking spots",
                            ),
                            ("Parks and playgrounds", "Parks and playgrounds"),
                            (
                                "Parades or community gatherings",
                                "Parades or community gatherings",
                            ),
                            ("Picnic areas", "Picnic areas"),
                            ("Planetariums", "Planetariums"),
                            (
                                "Professional Sporting Event",
                                "Professional Sporting Event",
                            ),
                            (
                                "Shopping centers with kid-friendly stores",
                                "Shopping centers with kid-friendly stores",
                            ),
                            (
                                "Sports complexes (for other sports)",
                                "Sports complexes (for other sports)",
                            ),
                            (
                                "Swimming pools or water parks",
                                "Swimming pools or water parks",
                            ),
                            ("Toy stores", "Toy stores"),
                            ("Trampoline parks", "Trampoline parks"),
                            ("Zoos and aquariums", "Zoos and aquariums"),
                        ],
                        default="Other",
                        max_length=100,
                    ),
                ),
                (
                    "age_range",
                    models.CharField(
                        choices=[
                            ("8u", "8 and under"),
                            ("10u", "10 and under"),
                            ("12u", "12 and under"),
                            ("14u", "14 and under"),
                            ("16u", "16 and under"),
                            ("18u", "18 and under"),
                        ],
                        default="8u",
                        max_length=4,
                    ),
                ),
                (
                    "service_quality_rating",
                    models.CharField(
                        choices=[("Good", "Good"), ("Bad", "Bad")],
                        default="Good",
                        max_length=4,
                    ),
                ),
                (
                    "serving_alcohol",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("All", "All"),
                            ("Beer", "Beer"),
                            ("Wine", "Wine"),
                            ("Liquor", "Liquor"),
                        ],
                        default="None",
                        max_length=10,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("All", "All"),
                            ("Card", "Card"),
                            ("Cash", "Cash"),
                            ("Apple Pay / Google Pay", "Apple Pay / Google Pay"),
                        ],
                        default="None",
                        max_length=22,
                    ),
                ),
                (
                    "parking_size",
                    models.CharField(
                        choices=[
                            ("Small", "Small"),
                            ("Medium", "Medium"),
                            ("Large", "Large"),
                        ],
                        default="Medium",
                        max_length=6,
                    ),
                ),
                (
                    "entertainment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entertainments.entertainment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RestaurantReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date_of_review", models.DateField()),
                (
                    "review_text",
                    models.TextField(
                        default="n/a",
                        validators=[django.core.validators.MaxLengthValidator(1200)],
                    ),
                ),
                (
                    "thumb_updown",
                    models.CharField(
                        choices=[
                            ("Thumbs Up", "Thumbs Up"),
                            ("Thumbs Down", "Thumbs Down"),
                        ],
                        default="Thumbs Up",
                        max_length=11,
                    ),
                ),
                (
                    "meal_quality_rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=5.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "service_quality_rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=5.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "seating_time",
                    models.PositiveIntegerField(
                        choices=[
                            (10, "10 minutes"),
                            (20, "20 minutes"),
                            (30, "30 minutes"),
                            (40, "40 minutes"),
                            (50, "50 minutes"),
                            (60, "1 hour"),
                            (70, "1 hour 10 minutes"),
                            (80, "1 hour 20 minutes"),
                            (90, "1 hour 30 minutes"),
                        ],
                        default=30,
                    ),
                ),
                (
                    "payment_process",
                    models.CharField(
                        choices=[
                            ("Smooth", "Smooth"),
                            ("Average", "Average"),
                            ("Rough", "Rough"),
                        ],
                        default="Smooth",
                        max_length=100,
                    ),
                ),
                (
                    "parking_size",
                    models.CharField(
                        choices=[
                            ("Small", "Small"),
                            ("Medium", "Medium"),
                            ("Large", "Large"),
                        ],
                        default="Medium",
                        max_length=50,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
