# Generated by Django 5.0.1 on 2024-01-19 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_remove_tournament_director_communication_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='date',
            new_name='date_of_visit',
        ),
    ]
