# Generated by Django 5.0.1 on 2024-01-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_rename_date_review_date_of_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='parking_notes',
            field=models.TextField(default='', help_text='Anything worth noting about the parking when you visited?', max_length=250),
        ),
    ]
