# Generated by Django 5.0.1 on 2024-01-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_alter_review_parking_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
        migrations.AddField(
            model_name='review',
            name='experience',
            field=models.TextField(default='', help_text='This is what will be displayed as your main review. (250 words max)', max_length=250),
        ),
        migrations.AlterField(
            model_name='review',
            name='parking_notes',
            field=models.TextField(default='', help_text='Anything that would help others in the future?', max_length=250),
        ),
    ]
