# Generated by Django 5.0.1 on 2024-01-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_remove_review_text_review_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='experience',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='review',
            name='parking_notes',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
    ]
