# Generated by Django 5.0.1 on 2024-01-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_alter_review_experience_alter_review_parking_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='director_communication_average',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Below Average', 'Below Average'), ('Average', 'Average'), ('Above Average', 'Above Average'), ('Excellent', 'Excellent')], default='Excellent', max_length=15),
        ),
        migrations.AddField(
            model_name='tournament',
            name='hotel_quality_average',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Below Average', 'Below Average'), ('Average', 'Average'), ('Above Average', 'Above Average'), ('Excellent', 'Excellent')], default='Excellent', max_length=15),
        ),
        migrations.AddField(
            model_name='tournament',
            name='reffing_quality_average',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Below Average', 'Below Average'), ('Average', 'Average'), ('Above Average', 'Above Average'), ('Excellent', 'Excellent')], default='Excellent', max_length=15),
        ),
    ]
