# Generated by Django 5.0.1 on 2024-01-22 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_tournament_director_communication_average_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_of_entertainment', models.CharField(choices=[('Arcade/Fun Zone', 'Arcade/Fun Zone'), ('Pro Sport Event', 'Pro Sport Event'), ('College Sport Event', 'College Sport Event'), ('Festival', 'Festival')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='EntertainmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('activities', models.CharField(default='None', max_length=255)),
                ('party_size', models.CharField(choices=[('10-15', '10-15 people'), ('15-25', '15-25 people'), ('25-35', '25-35 people')], max_length=10)),
                ('customer_service', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1)),
                ('large_group_deals', models.BooleanField()),
                ('food_quality', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1)),
                ('parking', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=6)),
                ('parking_notes', models.TextField(max_length=150)),
                ('rating', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.entertainment')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('type_of_food', models.CharField(choices=[('American', 'American'), ('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Chinese', 'Chinese'), ('Korean', 'Korean'), ('Japanese', 'Japanese'), ('Indian', 'Indian'), ('Mediterranean', 'Mediterranean'), ('Thai', 'Thai')], max_length=13)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('diet_friendly', models.CharField(choices=[('None', 'None'), ('Gluten-Free', 'Gluten-Free'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian')], max_length=11)),
                ('party_size', models.CharField(choices=[('10-15', '10-15 people'), ('15-25', '15-25 people'), ('25-35', '25-35 people')], max_length=10)),
                ('customer_service', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1)),
                ('waiting_seat_time', models.IntegerField(choices=[('15', '15 mins'), ('30', '30 mins'), ('40', '45 mins')])),
                ('waiting_food_time', models.IntegerField(choices=[('15', '15 mins'), ('30', '30 mins'), ('40', '45 mins')])),
                ('food_quality', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1)),
                ('check_splitting', models.CharField(choices=[('easy', 'easy'), ('player_jersey', 'went by player jersey number'), ('complicated', 'complicated')], max_length=30)),
                ('parking', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=6)),
                ('parking_notes', models.TextField(max_length=150)),
                ('rating', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.restaurant')),
            ],
        ),
    ]
