# Generated by Django 5.0.1 on 2024-01-23 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_restaurantsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntertainmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewing', 'Reviewing'), ('Approved', 'Approved'), ('Archived', 'Archived')], default='Pending', max_length=15)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
