# Generated by Django 5.0.1 on 2024-04-19 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0044_remove_rink_parking_type_remove_rink_tournament_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('director_present', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ("I don't Know", "I don't Know")], default="I Don't Know", max_length=12)),
                ('rink_temp', models.CharField(choices=[('Shorts & Hoodies', 'Shorts & Hoodies'), ('Linen Pants & Heavy Jacket', 'Linen Pants & Heavy Jackets'), ('Moms Bring Your Blankets!', 'Moms Bring Your Blankets!')], default='Shorts & Hoodies', max_length=50)),
                ('parking_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='Medium', max_length=100)),
                ('valet_parking', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ("I don't Know", "I don't Know")], default="I Don't Know", max_length=12)),
                ('parking_cost', models.CharField(choices=[('free', 'Free'), ('$0-$5', '$0 - $5'), ('$5-$10', '$5 - $10'), ('$10-$15', '$10 - $15'), ('$15-$20', '$15 - $20'), ('$20-$25', '$20 - $25'), ('$25-$30', '$25 - $30')], default='Free', max_length=15)),
                ('snack_bar', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ("I don't Know", "I don't Know")], default="I Don't Know", max_length=12)),
                ('pro_shop', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ("I don't Know", "I don't Know")], default="I Don't Know", max_length=12)),
                ('bathroom_state', models.CharField(choices=[('Pretty Clean', 'Pretty Clean'), ('Average', 'Average'), ('Nothing to Rave Home About', 'Nothing to Rave Home About'), ('Hose Shoes Off After Walk You Out', 'Hose Shoes Off After Walk You Out')], default='Pretty Clean', max_length=33)),
                ('parking_type', models.ManyToManyField(blank=True, to='rink.parkingavailability')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
    ]
