# Generated by Django 5.0.1 on 2024-04-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rink', '0002_paymentmodes_rink_payment_modes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RinkNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='rink',
            name='skate_sharpening',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ("I don't Know", "I don't Know")], default="I Don't Know", max_length=12),
        ),
        migrations.AlterField(
            model_name='rink',
            name='rink_temp',
            field=models.CharField(choices=[('Shorts & Hoodies', 'Shorts & Hoodies'), ('Pants & Heavy Jacket', 'Pants & Heavy Jackets'), ('Moms Bring Your Blankets!', 'Moms Bring Your Blankets!')], default='Shorts & Hoodies', max_length=50),
        ),
        migrations.AddField(
            model_name='rink',
            name='offers_needs',
            field=models.ManyToManyField(blank=True, to='rink.rinkneed'),
        ),
    ]
