# Generated by Django 5.0.1 on 2024-04-19 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rink', '0003_rinkneed_rink_skate_sharpening_alter_rink_rink_temp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rink',
            name='skate_sharpening',
        ),
    ]
