# Generated by Django 5.0.1 on 2024-04-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rink', '0005_alter_rink_rink_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rink',
            name='rink_temp',
            field=models.CharField(choices=[('Shorts & Hoodie', 'Shorts & Hoodie'), ('Pants & Heavy Jacket', 'Pants & Heavy Jackets'), ('Moms Bring Your Blankets!', 'Moms Bring Your Blankets!')], default='Shorts & Hoodie', max_length=50),
        ),
    ]
