# Generated by Django 5.0.1 on 2024-04-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rink', '0006_alter_rink_rink_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rink',
            name='bathroom_state',
            field=models.CharField(choices=[("I don't Know", "I don't Know"), ('Pretty Clean', 'Pretty Clean'), ('Average', 'Average'), ('Nothing to Rave Home About', 'Nothing to Rave Home About'), ('Hose Shoes Off After Walk You Out', 'Hose Shoes Off After Walk You Out')], default='Pretty Clean', max_length=33),
        ),
        migrations.AlterField(
            model_name='rink',
            name='parking_cost',
            field=models.CharField(choices=[("I don't Know", "I don't Know"), ('Free', 'Free'), ('$0-$5', '$0 - $5'), ('$5-$10', '$5 - $10'), ('$10-$15', '$10 - $15'), ('$15-$20', '$15 - $20'), ('$20-$25', '$20 - $25'), ('$25-$30', '$25 - $30')], default='Free', max_length=15),
        ),
        migrations.AlterField(
            model_name='rink',
            name='parking_size',
            field=models.CharField(choices=[("I don't Know", "I don't Know"), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='Medium', max_length=100),
        ),
        migrations.AlterField(
            model_name='rink',
            name='rink_temp',
            field=models.CharField(choices=[("I don't Know", "I don't Know"), ('Shorts & Hoodie', 'Shorts & Hoodie'), ('Pants & Heavy Jacket', 'Pants & Heavy Jackets'), ('Moms Bring Your Blankets!', 'Moms Bring Your Blankets!')], default='Shorts & Hoodie', max_length=50),
        ),
    ]
