# Generated by Django 5.0.1 on 2024-03-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.CharField(default='https://www.yhtreviews.com', max_length=100),
        ),
    ]
