# Generated by Django 5.0.1 on 2024-03-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_restaurant_food_type_alter_restaurant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='food_type',
            field=models.CharField(choices=[('American', 'American'), ('Brazilian', 'Brazilian'), ('British', 'British'), ('Cajun', 'Cajun'), ('Caribbean', 'Caribbean'), ('Chinese', 'Chinese'), ('French', 'French'), ('German', 'German'), ('Greek', 'Greek'), ('Indian', 'Indian'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Mediterranean', 'Mediterranean'), ('Mexican', 'Mexican'), ('Middle Eastern', 'Middle Eastern'), ('Southern', 'Southern'), ('Spanish', 'Spanish'), ('Thai', 'Thai'), ('Vietnamese', 'Vietnamese')], max_length=100),
        ),
    ]
