# Generated by Django 5.0.1 on 2024-03-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_restaurant_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='parking_size',
            field=models.CharField(choices=[('Street', 'Street'), ('Meter', 'Meter'), ('Lot', 'Lot')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='seating_time',
            field=models.CharField(choices=[('15 minutes', '15 minutes'), ('30 minutes', '30 minutes'), ('30 minutes', '30 minutes'), ('45 minutes', '45 minutes'), ('60 minutes', '60 minutes'), ('90 minutes', '90 minutes')], default='30 minutes', max_length=25),
        ),
    ]
