# Generated by Django 5.0.1 on 2024-03-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_restaurant_parking_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='serving_time',
            field=models.CharField(choices=[('15 minutes', '15 minutes'), ('30 minutes', '30 minutes'), ('30 minutes', '30 minutes'), ('45 minutes', '45 minutes'), ('60 minutes', '60 minutes'), ('90 minutes', '90 minutes')], default='30 minutes', max_length=25),
        ),
    ]
