# Generated by Django 5.0.1 on 2024-04-13 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_restaurant_serving_time'),
        ('tournament', '0023_rink'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament'),
        ),
    ]
