# Generated by Django 5.0.1 on 2024-04-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_restaurant_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='seating_time',
            field=models.CharField(choices=[('15 minutes', '15 minutes'), ('30 minutes', '30 minutes'), ('45 minutes', '45 minutes'), ('60 minutes', '60 minutes'), ('90 minutes', '90 minutes')], default='30 minutes', max_length=25),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='serving_time',
            field=models.CharField(choices=[('15 minutes', '15 minutes'), ('30 minutes', '30 minutes'), ('45 minutes', '45 minutes'), ('60 minutes', '60 minutes'), ('90 minutes', '90 minutes')], default='30 minutes', max_length=25),
        ),
    ]
