# Generated by Django 5.0.1 on 2024-03-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_type', models.CharField(choices=[('Tournament', 'Promote Tournament'), ('Restaurant', 'Promote Restaurant'), ('Hotel', 'Promote Hotel'), ('Entertainment', 'Promote Entertainment')], max_length=20)),
                ('place_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
            ],
        ),
    ]
