# Generated by Django 5.0.1 on 2024-03-22 20:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0009_alter_tournament_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('website', models.CharField(default='https://www.yhtreviews.com', max_length=100)),
                ('activity_type', models.CharField(choices=[('Arts and Crafts', 'Arts and Crafts'), ('Brewery', 'Brewery'), ('Class', 'Class'), ('Comedy Show', 'Comedy Show'), ('Concert', 'Concert'), ('Cooking Demonstration', 'Cooking Demonstration'), ('Cultural Event', 'Cultural Event'), ('Dance Performance', 'Dance Performance'), ('Exhibition', 'Exhibition'), ('Festival', 'Festival'), ('Food Tasting', 'Food Tasting'), ('Game', 'Game'), ('Movie', 'Movie'), ('Outdoor', 'Outdoor'), ('Other', 'Other'), ('Party', 'Party'), ('Race', 'Race'), ('Show', 'Show'), ('Tour', 'Tour'), ('Vineyard', 'Vineyard'), ('Winery', 'Winery'), ('Workshop', 'Workshop')], max_length=100)),
                ('age_range', models.CharField(choices=[('U8', 'U8'), ('U10', 'U10'), ('U12', 'U12'), ('U14', 'U14'), ('U16', 'U16'), ('U18', 'U18'), ('U20', 'U20'), ('U21', 'U21'), ('U23', 'U23')], max_length=3)),
                ('serve_beer', models.BooleanField(default=False)),
                ('serve_wine', models.BooleanField(default=False)),
                ('serve_liquor', models.BooleanField(default=False)),
                ('take_cash', models.BooleanField(default=False)),
                ('take_card', models.BooleanField(default=False)),
                ('take_digital_payment', models.BooleanField(default=False)),
                ('service_rating', models.FloatField(default=4.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('parking_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('draft_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.location')),
            ],
        ),
    ]
