# Generated by Django 5.0.1 on 2024-04-13 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0003_entertainment_description'),
        ('tournament', '0023_rink'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainment',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament'),
        ),
    ]
