# Generated by Django 5.0.1 on 2024-04-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0004_entertainment_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainment',
            name='parking_size',
            field=models.CharField(choices=[("I don't Know", "I don't Know"), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=12),
        ),
    ]
