# Generated by Django 5.0.1 on 2024-01-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_city_location_country_location_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'city', 'state')},
        ),
    ]
